const langues = {
    "fr": {
        "pourquoi": "Je remplis cette attestation à chaque fois que je sors. C'est la loi pour le coronavirus.",
        "choix-langue": "Choix de la langue",
        "texte-champs-obligatoires": "Tous les champs sont obligatoires",
        "prenom-label": "Prénom",
        "prenom": "Prénom",
        "nom-label": "Nom",
        "nom": "Nom",
        "date_naissance-label": "Date de naissance",
        "date_naissance": "Date de naissance",
        "lieu_naissance-label": "Lieu de naissance",
        "lieu_naissance": "Lieu de naissance",
        "adresse-label": "Adresse",
        "adresse": "Adresse",
        "ville-label": "Ville",
        "ville": "Ville",
        "code_postal-label": "Code postal",
        "code_postal": "Code postal",
        "titre_motifs": "Choisissez le ou les motifs de sortie / Je sors pour:",
        "texte-travail": "Aller travailler",
        "texte-courses": "Acheter à manger.",
        "texte-sante": "Aller chez le docteur ou à la pharmacie",
        "texte-famille": "M’occuper d’une personne qui a besoin de moi.",
        "texte-sport": "Sortir peu de temps pas loin de chez moi. Sortir mon chien.",
        "texte-judiciaire": "Convocation administrative ou judiciaire.",
        "texte-missions": "Participer à des missions d'intérêt général à la demande de l'autorité administrative.",
        "date_sortie-label": "Date de sortie",
        "heure_sortie-label": "Heure de sortie",
        "generer-attestation": "Génération attestation"

    },
    "en": {
        "pourquoi": "I fill this out every time I go out. It's the law for coronavirus.",
        "choix-langue": "Choose language",
        "texte-champs-obligatoires": "All fields are mandatory",
        "prenom-label": "First name",
        "prenom": "First name",
        "nom-label": "Last name",
        "nom": "Last name",
        "date_naissance-label": "Birthdate",
        "date_naissance": "Birthdate",
        "lieu_naissance-label": "Birthplace",
        "lieu_naissance": "Birthplace",
        "adresse-label": "Address",
        "adresse": "Address",
        "ville-label": "City",
        "ville": "City",
        "code_postal-label": "Zip code",
        "code_postal": "Zip code",
        "titre_motifs": "Choose the reason(s) for / I'm going out for:",
        "texte-travail": "Go to work",
        "texte-courses": "Buying some food",
        "texte-sante": "Going to the pharmacy or to the doctor",
        "texte-famille": "Taking care of someone who needs me.",
        "texte-sport": "Going out for a short time not far from my house. Taking my dog out.",
        "texte-judiciaire": "Administrative or judicial summons.",
        "texte-missions": "Participate in missions of general interest at the request of the administrative authority.",
        "date_sortie-label": "Date",
        "heure_sortie-label": "Hour",
        "generer-attestation": "Generate certificate"
    },
    "es": {
        "pourquoi": "Acuerdo con la ley francesa, llenar este formulario cada vez que salgas de casa",
        "choix-langue": "Elija el idioma",
        "texte-champs-obligatoires": "Todos los campos son obligatorios",
        "prenom-label": "Nombre",
        "prenom": "Nombre",
        "nom-label": "Apellido",
        "nom": "Apellido",
        "date_naissance-label": "Fecha de nacimiento",
        "date_naissance": "Fecha de nacimiento",
        "lieu_naissance-label": "Lugar de nacimiento",
        "lieu_naissance": "Lugar de nacimiento",
        "adresse-label": "Domicilio",
        "adresse": "Domicilio",
        "ville-label": "Ciudad",
        "ville": "Ciudad",
        "code_postal-label": "Código postal",
        "code_postal": "Código postal",
        "titre_motifs": "Elija la(s) razón(es) de su salida:",
        "texte-travail": "Trabajo",
        "texte-courses": "Comprar comida",
        "texte-sante": "Ir a la farmacia o al médico",
        "texte-famille": "Desplazamiento para la asistencia de personas vulnerables o el cuidado de niños",
        "texte-sport": "Salir por un corto tiempo cerca de mi casa. Sacar a mi perro a pasear.",
        "texte-judiciaire": "Convocación administrativa o judicial.",
        "texte-missions": "Participación comunitaria por parte del estado.",
        "date_sortie-label": "Fecha de salida",
        "heure_sortie-label": "Hora de salida",
        "generer-attestation": "Crear atestación"
    },
    "pt": {
        "pourquoi": "Preencho esta declaração cada vez que saio de casa para cumprir a lei durante o coronavírus.",
        "choix-langue": "Escolha o idioma",
        "texte-champs-obligatoires": "Todos os campos são obrigatórios",
        "prenom-label": "Nome",
        "prenom": "Nome",
        "nom-label": "Apelido",
        "nom": "Apelido",
        "date_naissance-label": "Data de nascimento",
        "date_naissance": "Data de nascimento",
        "lieu_naissance-label": "Local de nascimento",
        "lieu_naissance": "Local de nascimento",
        "adresse-label": "Morada",
        "adresse": "Morada",
        "ville-label": "Localidade",
        "ville": "Localidade",
        "code_postal-label": "Código postal",
        "code_postal": "Código postal",
        "titre_motifs": "Selecione o(s) motivo(s) da saída / Eu saio para:",
        "texte-travail": "Ir trabalhar",
        "texte-courses": "Ir às compras",
        "texte-sante": "Ir ao médico ou à farmácia",
        "texte-famille": "Prestar assistência a uma pessoa que necessita",
        "texte-sport": "Sair por pouco tempo perto de minha casa; passear o cão",
        "texte-judiciaire": "Convocatória administrativa ou judicial",
        "texte-missions": "Participar em missões de interesse geral por ordem de autoridade administrativa",
        "date_sortie-label": "Data da saída",
        "heure_sortie-label": "Hora da saída",
        "generer-attestation": "Gerar declaração"
    },
    "ar": {
        "pourquoi": "وفقًا للقانون الفرنسي أثناء الفيروس التاجي ، أحتاج إلى ملء هذا النموذج في كل مرة أخرج فيها",
        "choix-langue": "اختر اللغة",
        "texte-champs-obligatoires": "كل الحقول إلزامية",
        "prenom-label": "الاسم",
        "prenom": "الاسم",
        "nom-label": "اللقب او اسم العائلة",
        "nom": "اللقب او اسم العائلة",
        "date_naissance-label": "تاريخ الميلاد",
        "date_naissance": "تاريخ الميلاد",
        "lieu_naissance-label": "مكان الميلاد",
        "lieu_naissance": "مكان الميلاد",
        "adresse-label": "العنوان",
        "adresse": "العنوان",
        "ville-label": "المدينة",
        "ville": "المدينة",
        "code_postal-label": "الرمز البريدي",
        "code_postal": "الرمز البريدي",
        "titre_motifs": ":برجاء اختيار سبب او أسباب الخروج / انا خارج للاتي",
        "texte-travail": "للعمل",
        "texte-courses": "شراء مأكولات",
        "texte-sante": "للذهاب للطبيب. للذهاب للصيدلية",
        "texte-famille": "للاهتمام بشخص يحتاجني",
        "texte-sport": "للخروج بعض الوقت ليس بعيدا عن مسكني. لتخريج الكلب",
        "texte-judiciaire": "استدعاء قانوني او إداري",
        "texte-missions": "المساهمة في مهمات ذات طابع عام وبلب من الجهة الإدارية",
        "date_sortie-label": "تاريخ الخروج",
        "heure_sortie-label": "ساعة الخروج",
        "generer-attestation": "إنشاء الشهادة"
    }
};
