const langues = {
    "fr": {
        "pourquoi": "Je remplis cette attestation à chaque fois que je sors. C'est la loi pour le coronavirus.",
        "choix-langue": "Choix de la langue",
        "texte-champs-obligatoires": "Tous les champs sont obligatoires",
        "prenom-label": "Prénom",
        "prenom": "Prénom",
        "nom-label": "Nom",
        "nom": "Nom",
        "date_naissance-label": "Date de naissance",
        "date_naissance": "Date de naissance",
        "lieu_naissance-label": "Lieu de naissance",
        "lieu_naissance": "Lieu de naissance",
        "adresse-label": "Adresse",
        "adresse": "Adresse",
        "ville-label": "Ville",
        "ville": "Ville",
        "code_postal-label": "Code postal",
        "code_postal": "Code postal",
        "titre_motifs": "Choisissez le ou les motifs de sortie / Je sors pour:",
        "texte-travail": "Aller travailler",
        "texte-courses": "Acheter à manger.",
        "texte-sante": "Aller chez le docteur ou à la pharmacie",
        "texte-famille": "M’occuper d’une personne qui a besoin de moi.",
        "texte-sport": "Sortir peu de temps pas loin de chez moi. Sortir mon chien.",
        "texte-judiciaire": "Convocation administrative ou judiciaire.",
        "texte-missions": "Participer à des missions d'intérêt général à la demande de l'autorité administrative.",
        "date_sortie-label": "Date de sortie",
        "heure_sortie-label": "Heure de sortie",
        "generer-attestation": "Génération attestation"

    },
    "en": {
        "pourquoi": "I fill this out every time I go out. It's the law for coronavirus.",
        "choix-langue": "Choose language",
        "texte-champs-obligatoires": "All fields are mandatory",
        "prenom-label": "First name",
        "prenom": "First name",
        "nom-label": "Last name",
        "nom": "Last name",
        "date_naissance-label": "Birthdate",
        "date_naissance": "Birthdate",
        "lieu_naissance-label": "Birthplace",
        "lieu_naissance": "Birthplace",
        "adresse-label": "Address",
        "adresse": "Address",
        "ville-label": "City",
        "ville": "City",
        "code_postal-label": "Zip code",
        "code_postal": "Zip code",
        "titre_motifs": "Choose the reason(s) for / I'm going out for:",
        "texte-travail": "Go to work",
        "texte-courses": "Buying some food",
        "texte-sante": "Going to the pharmacy or to the doctor",
        "texte-famille": "Taking care of someone who needs me.",
        "texte-sport": "Going out for a short time not far from my house. Taking my dog out.",
        "texte-judiciaire": "Administrative or judicial summons.",
        "texte-missions": "Participate in missions of general interest at the request of the administrative authority.",
        "date_sortie-label": "Date",
        "heure_sortie-label": "Hour",
        "generer-attestation": "Generate certificate"
    }
    
};
